#cloud-config
package_update: true

runcmd:
  # Disable swap
  - swapoff -a
  - sed -i '/ swap / s/^/#/' /etc/fstab

  # Kernel modules
  - modprobe overlay
  - modprobe br_netfilter
  - |
      cat <<EOF | tee /etc/modules-load.d/containerd.conf
      overlay
      br_netfilter
      EOF

  # Sysctl
  - |
      cat <<EOF | tee /etc/sysctl.d/99-kubernetes-cri.conf
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1
      EOF
  - sysctl --system

  # Install containerd
  - yum install -y containerd
  - |
      containerd config default | tee /etc/containerd/config.toml >/dev/null
  - sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
  - systemctl enable --now containerd

  # Kubernetes repo
  - |
      cat <<EOF | tee /etc/yum.repos.d/kubernetes.repo
      [kubernetes]
      name=Kubernetes
      baseurl=https://pkgs.k8s.io/core:/stable:/v1.30/rpm/
      enabled=1
      gpgcheck=1
      gpgkey=https://pkgs.k8s.io/core:/stable:/v1.30/rpm/repomd.xml.key
      EOF

  # Install kubelet + kubeadm
  - yum install -y kubelet kubeadm --disableexcludes=kubernetes
  - systemctl enable --now kubelet

  # Get join command from SSM and join cluster
  - |
      JOIN_CMD=$(aws ssm get-parameter \
        --name "k8sJoinCommand" \
        --query "Parameter.Value" \
        --output text \
        --region ap-south-1)
      $JOIN_CMD
