#cloud-config
package_update: true
package_upgrade: true

runcmd:
  - swapoff -a
  - sed -i '/ swap / s/^/#/' /etc/fstab

  - echo -e "overlay\nbr_netfilter" > /etc/modules-load.d/k8s.conf
  - modprobe overlay
  - modprobe br_netfilter

  - |
    cat <<EOF > /etc/sysctl.d/k8s.conf
    net.bridge.bridge-nf-call-iptables=1
    net.bridge.bridge-nf-call-ip6tables=1
    net.ipv4.ip_forward=1
    EOF

  - sysctl --system

  - dnf install -y crio
  - systemctl enable --now crio

  # Install Kubernetes binaries
  - curl -LO https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubeadm
  - curl -LO https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubelet
  - curl -LO https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
  - install -o root -g root -m 0755 kube* /usr/local/bin/

  - mkdir -p /etc/systemd/system/kubelet.service.d/

  - |
    cat <<EOF > /etc/systemd/system/kubelet.service
    [Unit]
    Description=kubelet
    After=crio.service
    Requires=crio.service

    [Service]
    ExecStart=/usr/local/bin/kubelet
    Restart=always

    [Install]
    WantedBy=multi-user.target
    EOF

  - systemctl daemon-reload
  - systemctl enable --now kubelet

  # -------- Get join command --------
  - JOIN_CMD=$(aws ssm get-parameter --name "k8sJoinCommand" --query "Parameter.Value" --output text --region ap-south-1)

  # -------- Join cluster --------
  - bash -c "$JOIN_CMD"
