#cloud-config

package_update: true
package_upgrade: true

runcmd:
  # -------- Disable Swap --------
  - swapoff -a
  - sed -i '/ swap / s/^/#/' /etc/fstab

  # -------- Kernel Modules --------
  - echo -e "overlay\nbr_netfilter" | tee /etc/modules-load.d/k8s.conf
  - modprobe overlay
  - modprobe br_netfilter

  # -------- Sysctl --------
  - |
    cat <<EOF > /etc/sysctl.d/k8s.conf
    net.bridge.bridge-nf-call-iptables=1
    net.bridge.bridge-nf-call-ip6tables=1
    net.ipv4.ip_forward=1
    EOF
  - sysctl --system

  # -------- Install containerd --------
  - dnf install -y containerd
  - containerd config default | tee /etc/containerd/config.toml
  - sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
  - systemctl enable --now containerd

  # -------- Kubernetes Repo --------
  - |
    cat <<EOF > /etc/yum.repos.d/kubernetes.repo
    [kubernetes]
    name=Kubernetes
    baseurl=https://pkgs.k8s.io/core:/stable:/v1.30/rpm/
    enabled=1
    gpgcheck=1
    gpgkey=https://pkgs.k8s.io/core:/stable:/v1.30/rpm/repomd.xml.key
    EOF

  # -------- Install kubelet + kubeadm --------
  - dnf install -y kubelet kubeadm --disableexcludes=kubernetes
  - systemctl enable --now kubelet

  # -------- Fetch join command from SSM --------
  - JOIN_CMD=$(aws ssm get-parameter --name "k8sJoinCommand" --query "Parameter.Value" --output text --region ap-south-1)

  # -------- Join Kubernetes Cluster --------
  - bash -c "$JOIN_CMD"
